(function(pokemonNamesJson) {
    const LS_CAUGHT_POKEMON_KEY = "caughtPokemon";
    const POKEMON_SPAWN_INTERVAL = 1000;
    const POKEMON_NAMES = JSON.parse(atob(pokemonNamesJson));
    const IMG_DIM_PX = 100;

    function saveCaughtPokemonNames(pokemonNames) {
        localStorage.setItem(LS_CAUGHT_POKEMON_KEY, JSON.stringify(pokemonNames));
    }

    function loadCaughtPokemonNames() {
        const caughtPokemonJson = localStorage.getItem(LS_CAUGHT_POKEMON_KEY);
        return caughtPokemonJson === null ? [] : JSON.parse(caughtPokemonJson);
    }

    function displayCaughtPokemon(pokemonName) {
        const img = document.createElement("img");
        img.src = `images/pokemon/${pokemonName}`;
        pokedexElement.append(img);
    }

    function getRandomIntInclusive(min, max) {
        min = Math.ceil(min);
        max = Math.floor(max);
        return Math.floor(Math.random() * (max - min + 1) + min); //The maximum is inclusive and the minimum is inclusive 
      }

    const pokedexElement = document.getElementById("pokedex-pokemon");
    const grassElement = document.getElementById("grass");
    let isPokemonVisible = false;
    const caughtPokemonNames = loadCaughtPokemonNames();

    for (const pokemonName of caughtPokemonNames) {
        displayCaughtPokemon(pokemonName);
    }

    setInterval(() => {
        if (isPokemonVisible) {
            return;
        }

        const spawnedPokemonName = POKEMON_NAMES[getRandomIntInclusive(0, POKEMON_NAMES.length - 1)];
        const pokemonElement = document.createElement("img");
        pokemonElement.className = "pokemon";
        pokemonElement.src = `images/pokemon/${spawnedPokemonName}`;
        pokemonElement.style = `position: relative; left:`
        pokemonElement.style.left = `${getRandomIntInclusive(IMG_DIM_PX, grassElement.clientWidth - IMG_DIM_PX)}px`;
        pokemonElement.style.top = `${getRandomIntInclusive(IMG_DIM_PX, grassElement.clientHeight - IMG_DIM_PX)}px`;
        pokemonElement.addEventListener("click", () => {
            caughtPokemonNames.push(spawnedPokemonName);
            saveCaughtPokemonNames(caughtPokemonNames);
            displayCaughtPokemon(spawnedPokemonName);
            grassElement.removeChild(pokemonElement);
            isPokemonVisible = false;
        });
        grassElement.append(pokemonElement);

        isPokemonVisible = true;
    }, POKEMON_SPAWN_INTERVAL)

})(`WyIxLmdpZiIsDQoiMTAuZ2lmIiwNCiIxMDAuZ2lmIiwNCiIxMDEuZ2lmIiwNCiIxMDIuZ2lmIiwNCiIxMDMuZ2lmIiwNCiIxMDQuZ2lmIiwNCiIxMDUuZ2lmIiwNCiIxMDYuZ2lmIiwNCiIxMDcuZ2lmIiwNCiIxMDguZ2lmIiwNCiIxMDkuZ2lmIiwNCiIxMS5naWYiLA0KIjExMC5naWYiLA0KIjExMS5naWYiLA0KIjExMi5naWYiLA0KIjExMy5naWYiLA0KIjExNC5naWYiLA0KIjExNS5naWYiLA0KIjExNi5naWYiLA0KIjExNy5naWYiLA0KIjExOC5naWYiLA0KIjExOS5naWYiLA0KIjEyLmdpZiIsDQoiMTIwLmdpZiIsDQoiMTIxLmdpZiIsDQoiMTIyLmdpZiIsDQoiMTIzLmdpZiIsDQoiMTI0LmdpZiIsDQoiMTI1LmdpZiIsDQoiMTI2LmdpZiIsDQoiMTI3LmdpZiIsDQoiMTI4LmdpZiIsDQoiMTI5LmdpZiIsDQoiMTMuZ2lmIiwNCiIxMzAuZ2lmIiwNCiIxMzEuZ2lmIiwNCiIxMzIuZ2lmIiwNCiIxMzMuZ2lmIiwNCiIxMzQuZ2lmIiwNCiIxMzUuZ2lmIiwNCiIxMzYuZ2lmIiwNCiIxMzcuZ2lmIiwNCiIxMzguZ2lmIiwNCiIxMzkuZ2lmIiwNCiIxNC5naWYiLA0KIjE0MC5naWYiLA0KIjE0MS5naWYiLA0KIjE0Mi5naWYiLA0KIjE0My5naWYiLA0KIjE0NC5naWYiLA0KIjE0NS5naWYiLA0KIjE0Ni5naWYiLA0KIjE0Ny5naWYiLA0KIjE0OC5naWYiLA0KIjE0OS5naWYiLA0KIjE1LmdpZiIsDQoiMTUwLmdpZiIsDQoiMTUxLmdpZiIsDQoiMTUyLmdpZiIsDQoiMTUzLmdpZiIsDQoiMTU0LmdpZiIsDQoiMTU1LmdpZiIsDQoiMTU2LmdpZiIsDQoiMTU3LmdpZiIsDQoiMTU4LmdpZiIsDQoiMTU5LmdpZiIsDQoiMTYuZ2lmIiwNCiIxNjAuZ2lmIiwNCiIxNjEuZ2lmIiwNCiIxNjIuZ2lmIiwNCiIxNjMuZ2lmIiwNCiIxNjQuZ2lmIiwNCiIxNjUuZ2lmIiwNCiIxNjYuZ2lmIiwNCiIxNjcuZ2lmIiwNCiIxNjguZ2lmIiwNCiIxNjkuZ2lmIiwNCiIxNy5naWYiLA0KIjE3MC5naWYiLA0KIjE3MS5naWYiLA0KIjE3Mi5naWYiLA0KIjE3My5naWYiLA0KIjE3NC5naWYiLA0KIjE3NS5naWYiLA0KIjE3Ni5naWYiLA0KIjE3Ny5naWYiLA0KIjE3OC5naWYiLA0KIjE3OS5naWYiLA0KIjE4LmdpZiIsDQoiMTgwLmdpZiIsDQoiMTgxLmdpZiIsDQoiMTgyLmdpZiIsDQoiMTgzLmdpZiIsDQoiMTg0LmdpZiIsDQoiMTg1LmdpZiIsDQoiMTg2LmdpZiIsDQoiMTg3LmdpZiIsDQoiMTg4LmdpZiIsDQoiMTg5LmdpZiIsDQoiMTkuZ2lmIiwNCiIxOTAuZ2lmIiwNCiIxOTEuZ2lmIiwNCiIxOTIuZ2lmIiwNCiIxOTMuZ2lmIiwNCiIxOTQuZ2lmIiwNCiIxOTUuZ2lmIiwNCiIxOTYuZ2lmIiwNCiIxOTcuZ2lmIiwNCiIxOTguZ2lmIiwNCiIxOTkuZ2lmIiwNCiIyLmdpZiIsDQoiMjAuZ2lmIiwNCiIyMDAuZ2lmIiwNCiIyMDEtYS5naWYiLA0KIjIwMS1iLmdpZiIsDQoiMjAxLWMuZ2lmIiwNCiIyMDEtZC5naWYiLA0KIjIwMS1lLmdpZiIsDQoiMjAxLWV4Y2xhbWF0aW9uLmdpZiIsDQoiMjAxLWYuZ2lmIiwNCiIyMDEtZy5naWYiLA0KIjIwMS1oLmdpZiIsDQoiMjAxLWkuZ2lmIiwNCiIyMDEtai5naWYiLA0KIjIwMS1rLmdpZiIsDQoiMjAxLWwuZ2lmIiwNCiIyMDEtbS5naWYiLA0KIjIwMS1uLmdpZiIsDQoiMjAxLW8uZ2lmIiwNCiIyMDEtcC5naWYiLA0KIjIwMS1xLmdpZiIsDQoiMjAxLXF1ZXN0aW9uLmdpZiIsDQoiMjAxLXIuZ2lmIiwNCiIyMDEtcy5naWYiLA0KIjIwMS10LmdpZiIsDQoiMjAxLXUuZ2lmIiwNCiIyMDEtdi5naWYiLA0KIjIwMS13LmdpZiIsDQoiMjAxLXguZ2lmIiwNCiIyMDEteS5naWYiLA0KIjIwMS16LmdpZiIsDQoiMjAyLmdpZiIsDQoiMjAzLmdpZiIsDQoiMjA0LmdpZiIsDQoiMjA1LmdpZiIsDQoiMjA2LmdpZiIsDQoiMjA3LmdpZiIsDQoiMjA4LmdpZiIsDQoiMjA5LmdpZiIsDQoiMjEuZ2lmIiwNCiIyMTAuZ2lmIiwNCiIyMTEuZ2lmIiwNCiIyMTIuZ2lmIiwNCiIyMTMuZ2lmIiwNCiIyMTQuZ2lmIiwNCiIyMTUuZ2lmIiwNCiIyMTYuZ2lmIiwNCiIyMTcuZ2lmIiwNCiIyMTguZ2lmIiwNCiIyMTkuZ2lmIiwNCiIyMi5naWYiLA0KIjIyMC5naWYiLA0KIjIyMS5naWYiLA0KIjIyMi5naWYiLA0KIjIyMy5naWYiLA0KIjIyNC5naWYiLA0KIjIyNS5naWYiLA0KIjIyNi5naWYiLA0KIjIyNy5naWYiLA0KIjIyOC5naWYiLA0KIjIyOS5naWYiLA0KIjIzLmdpZiIsDQoiMjMwLmdpZiIsDQoiMjMxLmdpZiIsDQoiMjMyLmdpZiIsDQoiMjMzLmdpZiIsDQoiMjM0LmdpZiIsDQoiMjM1LmdpZiIsDQoiMjM2LmdpZiIsDQoiMjM3LmdpZiIsDQoiMjM4LmdpZiIsDQoiMjM5LmdpZiIsDQoiMjQuZ2lmIiwNCiIyNDAuZ2lmIiwNCiIyNDEuZ2lmIiwNCiIyNDIuZ2lmIiwNCiIyNDMuZ2lmIiwNCiIyNDQuZ2lmIiwNCiIyNDUuZ2lmIiwNCiIyNDYuZ2lmIiwNCiIyNDcuZ2lmIiwNCiIyNDguZ2lmIiwNCiIyNDkuZ2lmIiwNCiIyNS5naWYiLA0KIjI1MC5naWYiLA0KIjI1MS5naWYiLA0KIjI1Mi5naWYiLA0KIjI1My5naWYiLA0KIjI1NC5naWYiLA0KIjI1NS5naWYiLA0KIjI1Ni5naWYiLA0KIjI1Ny5naWYiLA0KIjI1OC5naWYiLA0KIjI1OS5naWYiLA0KIjI2LmdpZiIsDQoiMjYwLmdpZiIsDQoiMjYxLmdpZiIsDQoiMjYyLmdpZiIsDQoiMjYzLmdpZiIsDQoiMjY0LmdpZiIsDQoiMjY1LmdpZiIsDQoiMjY2LmdpZiIsDQoiMjY3LmdpZiIsDQoiMjY4LmdpZiIsDQoiMjY5LmdpZiIsDQoiMjcuZ2lmIiwNCiIyNzAuZ2lmIiwNCiIyNzEuZ2lmIiwNCiIyNzIuZ2lmIiwNCiIyNzMuZ2lmIiwNCiIyNzQuZ2lmIiwNCiIyNzUuZ2lmIiwNCiIyNzYuZ2lmIiwNCiIyNzcuZ2lmIiwNCiIyNzguZ2lmIiwNCiIyNzkuZ2lmIiwNCiIyOC5naWYiLA0KIjI4MC5naWYiLA0KIjI4MS5naWYiLA0KIjI4Mi5naWYiLA0KIjI4My5naWYiLA0KIjI4NC5naWYiLA0KIjI4NS5naWYiLA0KIjI4Ni5naWYiLA0KIjI4Ny5naWYiLA0KIjI4OC5naWYiLA0KIjI4OS5naWYiLA0KIjI5LmdpZiIsDQoiMjkwLmdpZiIsDQoiMjkxLmdpZiIsDQoiMjkyLmdpZiIsDQoiMjkzLmdpZiIsDQoiMjk0LmdpZiIsDQoiMjk1LmdpZiIsDQoiMjk2LmdpZiIsDQoiMjk3LmdpZiIsDQoiMjk4LmdpZiIsDQoiMjk5LmdpZiIsDQoiMy5naWYiLA0KIjMwLmdpZiIsDQoiMzAwLmdpZiIsDQoiMzAxLmdpZiIsDQoiMzAyLmdpZiIsDQoiMzAzLmdpZiIsDQoiMzA0LmdpZiIsDQoiMzA1LmdpZiIsDQoiMzA2LmdpZiIsDQoiMzA3LmdpZiIsDQoiMzA4LmdpZiIsDQoiMzA5LmdpZiIsDQoiMzEuZ2lmIiwNCiIzMTAuZ2lmIiwNCiIzMTEuZ2lmIiwNCiIzMTIuZ2lmIiwNCiIzMTMuZ2lmIiwNCiIzMTQuZ2lmIiwNCiIzMTUuZ2lmIiwNCiIzMTYuZ2lmIiwNCiIzMTcuZ2lmIiwNCiIzMTguZ2lmIiwNCiIzMTkuZ2lmIiwNCiIzMi5naWYiLA0KIjMyMC5naWYiLA0KIjMyMS5naWYiLA0KIjMyMi5naWYiLA0KIjMyMy5naWYiLA0KIjMyNC5naWYiLA0KIjMyNS5naWYiLA0KIjMyNi5naWYiLA0KIjMyNy5naWYiLA0KIjMyOC5naWYiLA0KIjMyOS5naWYiLA0KIjMzLmdpZiIsDQoiMzMwLmdpZiIsDQoiMzMxLmdpZiIsDQoiMzMyLmdpZiIsDQoiMzMzLmdpZiIsDQoiMzM0LmdpZiIsDQoiMzM1LmdpZiIsDQoiMzM2LmdpZiIsDQoiMzM3LmdpZiIsDQoiMzM4LmdpZiIsDQoiMzM5LmdpZiIsDQoiMzQuZ2lmIiwNCiIzNDAuZ2lmIiwNCiIzNDEuZ2lmIiwNCiIzNDIuZ2lmIiwNCiIzNDMuZ2lmIiwNCiIzNDQuZ2lmIiwNCiIzNDUuZ2lmIiwNCiIzNDYuZ2lmIiwNCiIzNDcuZ2lmIiwNCiIzNDguZ2lmIiwNCiIzNDkuZ2lmIiwNCiIzNS5naWYiLA0KIjM1MC5naWYiLA0KIjM1MS5naWYiLA0KIjM1Mi5naWYiLA0KIjM1My5naWYiLA0KIjM1NC5naWYiLA0KIjM1NS5naWYiLA0KIjM1Ni5naWYiLA0KIjM1Ny5naWYiLA0KIjM1OC5naWYiLA0KIjM1OS5naWYiLA0KIjM2LmdpZiIsDQoiMzYwLmdpZiIsDQoiMzYxLmdpZiIsDQoiMzYyLmdpZiIsDQoiMzYzLmdpZiIsDQoiMzY0LmdpZiIsDQoiMzY1LmdpZiIsDQoiMzY2LmdpZiIsDQoiMzY3LmdpZiIsDQoiMzY4LmdpZiIsDQoiMzY5LmdpZiIsDQoiMzcuZ2lmIiwNCiIzNzAuZ2lmIiwNCiIzNzEuZ2lmIiwNCiIzNzIuZ2lmIiwNCiIzNzMuZ2lmIiwNCiIzNzQuZ2lmIiwNCiIzNzUuZ2lmIiwNCiIzNzYuZ2lmIiwNCiIzNzcuZ2lmIiwNCiIzNzguZ2lmIiwNCiIzNzkuZ2lmIiwNCiIzOC5naWYiLA0KIjM4MC5naWYiLA0KIjM4MS5naWYiLA0KIjM4Mi5naWYiLA0KIjM4My5naWYiLA0KIjM4NC5naWYiLA0KIjM4NS5naWYiLA0KIjM4Ni1ub3JtYWwuZ2lmIiwNCiIzODYtc3BlZWQuZ2lmIiwNCiIzODYuZ2lmIiwNCiIzOS5naWYiLA0KIjQuZ2lmIiwNCiI0MC5naWYiLA0KIjQxLmdpZiIsDQoiNDIuZ2lmIiwNCiI0My5naWYiLA0KIjQ0LmdpZiIsDQoiNDUuZ2lmIiwNCiI0Ni5naWYiLA0KIjQ3LmdpZiIsDQoiNDguZ2lmIiwNCiI0OS5naWYiLA0KIjUuZ2lmIiwNCiI1MC5naWYiLA0KIjUxLmdpZiIsDQoiNTIuZ2lmIiwNCiI1My5naWYiLA0KIjU0LmdpZiIsDQoiNTUuZ2lmIiwNCiI1Ni5naWYiLA0KIjU3LmdpZiIsDQoiNTguZ2lmIiwNCiI1OS5naWYiLA0KIjYuZ2lmIiwNCiI2MC5naWYiLA0KIjYxLmdpZiIsDQoiNjIuZ2lmIiwNCiI2My5naWYiLA0KIjY0LmdpZiIsDQoiNjUuZ2lmIiwNCiI2Ni5naWYiLA0KIjY3LmdpZiIsDQoiNjguZ2lmIiwNCiI2OS5naWYiLA0KIjcuZ2lmIiwNCiI3MC5naWYiLA0KIjcxLmdpZiIsDQoiNzIuZ2lmIiwNCiI3My5naWYiLA0KIjc0LmdpZiIsDQoiNzUuZ2lmIiwNCiI3Ni5naWYiLA0KIjc3LmdpZiIsDQoiNzguZ2lmIiwNCiI3OS5naWYiLA0KIjguZ2lmIiwNCiI4MC5naWYiLA0KIjgxLmdpZiIsDQoiODIuZ2lmIiwNCiI4My5naWYiLA0KIjg0LmdpZiIsDQoiODUuZ2lmIiwNCiI4Ni5naWYiLA0KIjg3LmdpZiIsDQoiODguZ2lmIiwNCiI4OS5naWYiLA0KIjkuZ2lmIiwNCiI5MC5naWYiLA0KIjkxLmdpZiIsDQoiOTIuZ2lmIiwNCiI5My5naWYiLA0KIjk0LmdpZiIsDQoiOTUuZ2lmIiwNCiI5Ni5naWYiLA0KIjk3LmdpZiIsDQoiOTguZ2lmIiwNCiI5OS5naWYiXQ`);